[tool.poetry]
name = "project-t"
version = "0.1.0"
description = ""
authors = ["No one"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-fasthtml = "^0.6.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
